runtime: nodejs

env: flex

handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\.(js|css|png|jpg|svg|ttf|ico|json))$ 
  static_files: dist/\1
  upload: dist/.*\.(js|css|png|jpg|svg|ttf|ico|json)$  # catch all handler to index.html
- url: /dist
  static_dir: dist
  # static_files: dist/index.html
  # upload: dist/index.html




env_variables:
  DB_USER: oneroof2
  DB_PASS: oneroof2
  DB_NAME: oneroof
  
  CLOUD_SQL_CONNECTION_NAME: oneroofapp:asia-northeast1:oneroof2



beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: oneroofapp:asia-northeast1:oneroof2

manual_scaling:
  instances: 1

network:
  session_affinity: true