runtime: nodejs14


handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\.(js|css|png|jpg|svg|ttf|ico|json))$ 
  static_files: dist/\1
  upload: dist/.*\.(js|css|png|jpg|svg|ttf|ico|json)$  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html


env_variables:
  DB_USER: "oneroof"
  DB_PASS: "oneroof"
  DB_NAME: "oneroof"
  CLOUD_SQL_CONNECTION_NAME: "oneroof-315600:asia-northeast2:oneroof"



beta_settings:
  cloud_sql_instances: "oneroof-315600:asia-northeast2:oneroof"
